morphology:
    cell:
        center: !!python/tuple [0,0]
        radius: 150
    soma:
        size: 10
    dends:
        narms: 12
        nsegs: 20
        diam: 0.5

physiology:
    Ra: 100
    pas:
        g: 0.008
        e: -60

synapses:
    inputs:
        excitatory:
            density: 15
            g1: 1
            g2: 0.2

