morphology:
    cell:
        radius: 150
        jitter: False
        jrange: 10
        rotate: True
    soma:
        size: 10
    dends:
        narms: 6
        ngens: 4
        dmin: 0.2
        dmax: 0.5
        nseg: 100

physiology:
    Ra: 100
    pas:
        g: 0.005
        e: -60
    kv:
        gmax: 50
        n_50: -20
        n_slope: -0.04
        ntau_50: -30
        ntau_slope: 0
        ntau_max: 1
        h_50: -60
        h_slope: 0.15
        htau_50: 0
        htau_slope: 0
        htau_max: 10
        nN: 1
    calrgc:
        shift: 15
        gbar: 0.008
    caldiff:

synapses:
    inputs:
        excitatory:
            density: 12
            dmin: None
            dmax: 0.67
            g1: 3
            g2: 1
        inhibitory:
            dmax: 0.67
            dmin: None
    outputs:
        inhibitory:
            density: 15
            dmin: 0.67
            dmax: None
            amp: 8
            thres: 0.07
            tau1: 10
            tau2: 3
            g: 0.015
        excitatory:
